### ISSUE TITLE
Transfering to Julia-Embedded

### ISSUE THREAD

**Issue by aminya** [Julia-Embedded/jlcross#3]
Dear @terasakisatoshi,
Would you like to transfer your repository to Julia-Embedded? I would give you owner access.
https://github.com/Julia-Embedded

**Comment by terasakisatoshi** [comment]
Hi, @aminya 
Thank you for finding this repository. 

I would like to know, what kind of benefits do I transfer this repository to Julia-Embedded rather than  maintenance of the status quo.

This is my first time to get such offer.

**Comment by terasakisatoshi** [comment]
- I also have a plan to modify the repository to maintain dockerfile for each version of Julia to succeed to build using docker-compose tips (see #4 ). So, could you wait for a few days before deciding to accept your offer or not ?

**Comment by aminya** [comment]
You're welcome.

So by transferring your repository to an organization, you still have access, and you don't lose anything. Two main benefits are:

- Users can find your repository easier, as it will appear in Julia-Embedded page next to other similar repositories related to embedded programming. By getting more traffic, search engines will tend to work better for organizations.
- Usually, it gives more credibility to repositories
- It allows others to contribute easier to the repositories and will encourage developers for involvement.

Also, we can revert if you didn't like it.

Sure! I look forward to hearing back. 😃

**Comment by terasakisatoshi** [comment]
@aminya Thank you for your explanation. 

I've just finished my task #4. 

I have one more question.

If I join your `Julia-Embedded`, which repository do I commit/maintain? 
This repository ? or  https://github.com/Julia-Embedded/jlcross ?

Thank you.

**Comment by aminya** [comment]
https://github.com/Julia-Embedded/jlcross is just a fork I made until you decide to move. If you want to transfer I will remove that fork, and your repository will be moved there. So in the end, there is one repository to maintain.

**Comment by terasakisatoshi** [comment]
@aminya Thank you. 
I understand.Then I will accept your offer.

**Comment by aminya** [comment]
Awesome, now you are a member. Follow this help for transferring:
https://help.github.jp/enterprise/2.11/user/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-a-repository-to-another-user-account-or-to-an-organization

Enter Julia-Embedded as the name of the organization

**Comment by terasakisatoshi** [comment]
Done

![image](https://user-images.githubusercontent.com/16760547/68928720-25611c00-07ce-11ea-85c2-53f459bfb6c9.png)

**Comment by aminya** [comment]
Thank you!
