### ISSUE TITLE
Build Julia on Raspberry Pi 4

### ISSUE THREAD

**Issue by akshayhiregoudar** [Julia-Embedded/jlcross#37]
I was looking to build Julia from source for a Raspberry Pi 4. Will the docker files for rpi4 be released anytime soon or is there a way I can use the docker files of rpi3 to build on rpi4?

**Comment by terasakisatoshi** [comment]
@akshayhiregoudar 

Yes, I could confirm the julia binary generated by `rpi3/Dockerfile-v1.4.1` runs on my RaspberryPi4 (see https://github.com/Julia-Embedded/jlcross/pull/36#issuecomment-623248233).

**Comment by akshayhiregoudar** [comment]
@terasakisatoshi 
Thank you for the update.
